apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: server
  template:
    metadata:
      labels:
        name: server
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: server
      containers:
        - name: penpot-backend
          image: docker.io/penpotapp/backend:2.2.0
          ports:
            - containerPort: 6060
              name: default
              protocol: TCP
          resources:
            requests:
              cpu: 300m
              memory: 1000Mi
            limits:
              cpu: 500m
              memory: 1200Mi
          volumeMounts:
            - mountPath: /opt/data/assets
              name: data
          env:
            - name: PENPOT_FLAGS
              value: "enable-registration enable-login-with-password disable-email-verification disable-smtp disable-prepl-server disable-cors enable-webhooks"
            - name: PENPOT_PUBLIC_URI
              value: "https://design.noynto.me"
            - name: PENPOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: KEY
                  name: server
            - name: PENPOT_DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: USERNAME
                  name: database
            - name: PENPOT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: database
            - name: PENPOT_DATABASE_URI
              value: "postgresql://database:5432/nglots"
            - name: PENPOT_ASSETS_STORAGE_BACKEND
              value: "assets-fs"
            - name: PENPOT_STORAGE_ASSETS_FS_DIRECTORY
              value: "/opt/data/assets"
            - name: PENPOT_REDIS_URI
              value: "redis://cache:6379/0"
            - name: PENPOT_TELEMETRY_ENABLED
              value: "true"